alias sudo="sudo "
alias ls="ls --color=auto"
alias ll="ls -l --color=auto"
alias la="ls -la --color=auto"
alias v="nvim "
alias kcat="kitty icat "
alias open="xdg-open "
alias pacm="sudo pacman "
alias wc="wl-copy "
alias wp="wl-paste "
alias zsh_home="cd /usr/local/share/zsh_sources/ "
alias kpcli="keepassxc-cli "
alias za="zathura "
alias tm="tmux "
