vim.opt.nu = true
vim.opt.rnu = true
vim.cmd "set clipboard+=unnamedplus"
vim.opt.shiftwidth = 0
vim.opt.tabstop = 4
vim.opt.foldmethod = 'expr'
vim.opt.foldexpr = 'nvim_treesitter#foldexpr()'
vim.cmd "set nofoldenable"
vim.opt.hls = false
vim.opt.termguicolors = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
